INSERT INTO articulos (nombre, precio, create_at) VALUES('Lapicero Fabell',2,NOW());
INSERT INTO articulos (nombre, precio, create_at) VALUES('Plumon Fabell',3,NOW());
INSERT INTO articulos (nombre, precio, create_at) VALUES('Tajador Aleman',3,NOW());
INSERT INTO articulos (nombre, precio, create_at) VALUES('Borrador',2,NOW());
INSERT INTO articulos (nombre, precio, create_at) VALUES('Estampilla 2x',1,NOW());
INSERT INTO articulos (nombre, precio, create_at) VALUES('Papel Celofan',1,NOW());
INSERT INTO articulos (nombre, precio, create_at) VALUES('Crayollas 24u',4,NOW());
INSERT INTO articulos (nombre, precio, create_at) VALUES('Plumones 12u',12,NOW());
INSERT INTO articulos (nombre, precio, create_at) VALUES('Cartulina A2',1,NOW());
INSERT INTO articulos (nombre, precio, create_at) VALUES('Cartulina A1',2,NOW());
INSERT INTO articulos (nombre, precio, create_at) VALUES('Escarapela',2,NOW());
INSERT INTO articulos (nombre, precio, create_at) VALUES('Bandera Nacional',4,NOW());
INSERT INTO articulos (nombre, precio, create_at) VALUES('Lapicero punta fina',4,NOW());
INSERT INTO articulos (nombre, precio, create_at) VALUES('Goma chico',2,NOW());
INSERT INTO articulos (nombre, precio, create_at) VALUES('Goma mediano',3,NOW());
INSERT INTO articulos (nombre, precio, create_at) VALUES('Goma grande',4,NOW());
INSERT INTO articulos (nombre, precio, create_at) VALUES('Papel Bonk 500h',24,NOW());
INSERT INTO articulos (nombre, precio, create_at) VALUES('Estuche 20j',10,NOW());
INSERT INTO articulos (nombre, precio, create_at) VALUES('Maleta escolar chico',12,NOW());
INSERT INTO articulos (nombre, precio, create_at) VALUES('Mochila mediano',15,NOW());